apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
data:
  example.org.conf: |
    server {
        listen 80;

        location / {
            proxy_pass http://93.184.216.34;
            proxy_set_header Host example.org;
            proxy_redirect "~^http[s]?:\/\/example.org\/(.*)$" $scheme://$http_host/$1;
        }
    }
